name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    env:
      GIT_SHA: ${{ github.sha }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.19.0

      - name: Build site
        run: ./build.sh

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "snen-dev"
          entrypoint: "./src/server/server.ts"
